apiVersion: apps/v1
kind: Deployment
metadata:
  name: blobs-api
  namespace: services
  labels:
    app: blobs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blobs-api
  template:
    metadata:
      labels:
        app: blobs-api
    spec:
      containers:
        - name: blobs-api
          image: registry.researchstack.info/control-plane/blobs-api:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
