apiVersion: v1
kind: Service
metadata:
  name: blobs-api
  namespace: services
  labels:
    app: blobs-api
spec:
  type: ClusterIP
  selector:
    app: blobs-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
