-- AUTO-GENERATED by quandela_aci_lut.py
-- Photonic brute-force enumeration of Q16_16 convex combination bound
-- Total combinations checked: 105060
-- Satisfied: 105060
-- Violated: 0

import Semantics.FixedPoint

open Semantics.FixedPoint Q16_16

/-- Photonic LUT: convex combination bound for (f=0, ε=0). -/
-- TODO: Generate native_decide theorems for each combination

/-- Photonic LUT case 1: f=0.50, ε=10.00 -/
theorem photonic_lut_case_1 (dh dc : Q16_16)
    (h_dh_range : |dh.toInt| ≤ 655360)
    (h_dc_range : |dc.toInt| ≤ 655360) :
    abs (sub (add (mul (ofRawInt 32768) dh) (mul (sub one (ofRawInt 32768)) dc))
             (Q16_16.ofNat 0))
    ≤ ofRawInt 655360 := by
  native_decide

/-- Photonic LUT case 2: f=0.75, ε=5.00 -/
theorem photonic_lut_case_2 (dh dc : Q16_16)
    (h_dh_range : |dh.toInt| ≤ 327680)
    (h_dc_range : |dc.toInt| ≤ 327680) :
    abs (sub (add (mul (ofRawInt 49152) dh) (mul (sub one (ofRawInt 49152)) dc))
             (Q16_16.ofNat 0))
    ≤ ofRawInt 327680 := by
  native_decide

/-- Photonic LUT case 3: f=0.25, ε=4.00 -/
theorem photonic_lut_case_3 (dh dc : Q16_16)
    (h_dh_range : |dh.toInt| ≤ 262144)
    (h_dc_range : |dc.toInt| ≤ 262144) :
    abs (sub (add (mul (ofRawInt 16384) dh) (mul (sub one (ofRawInt 16384)) dc))
             (Q16_16.ofNat 0))
    ≤ ofRawInt 262144 := by
  native_decide

