"""
Hermes Prometheus Metrics

Defines all Prometheus metrics for the Hermes orchestrator.

Author: Mistral Vibe
Version: 1.0.0
Date: 2026-06-01
"""

try:
    from prometheus_client import Counter, Histogram, Gauge, Summary
    PROMETHEUS_AVAILABLE = True
except ImportError:
    PROMETHEUS_AVAILABLE = False
    Counter = Histogram = Gauge = Summary = None


if PROMETHEUS_AVAILABLE:
    # Request counters
    request_counter = Counter(
        'hermes_requests_total',
        'Total Hermes inference requests',
        ['model', 'status']
    )
    
    # Request latency
    request_latency = Histogram(
        'hermes_request_latency_seconds',
        'Hermes inference request latency',
        ['model'],
        buckets=[0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 2, 5, 10, 30, 60]
    )
    
    # Token counters
    token_counter = Counter(
        'hermes_tokens_total',
        'Total tokens generated by Hermes',
        ['model', 'direction']  # direction: input or output
    )
    
    # Error counters
    error_counter = Counter(
        'hermes_errors_total',
        'Total Hermes errors',
        ['model', 'error_type']
    )
    
    # Active requests gauge
    active_requests_gauge = Gauge(
        'hermes_active_requests',
        'Number of active inference requests'
    )
    
    # Model loaded gauge
    models_loaded_gauge = Gauge(
        'hermes_models_loaded',
        'Number of models currently loaded',
        ['model']
    )
    
    # Queue size gauge
    queue_size_gauge = Gauge(
        'hermes_queue_size',
        'Number of requests in queue'
    )
    
    # Batch size summary
    batch_size_summary = Summary(
        'hermes_batch_size',
        'Batch request sizes'
    )
    
    # Circuit breaker state gauge
    circuit_breaker_state = Gauge(
        'hermes_circuit_breaker_state',
        'Circuit breaker state (0=closed, 1=open, 2=half_open)',
        ['model']
    )
else:
    # Dummy implementations when Prometheus is not available
    class DummyMetric:
        def labels(self, *args, **kwargs):
            return self
        def inc(self, *args, **kwargs):
            pass
        def observe(self, *args, **kwargs):
            pass
        def set(self, *args, **kwargs):
            pass
    
    request_counter = DummyMetric()
    request_latency = DummyMetric()
    token_counter = DummyMetric()
    error_counter = DummyMetric()
    active_requests_gauge = DummyMetric()
    models_loaded_gauge = DummyMetric()
    queue_size_gauge = DummyMetric()
    batch_size_summary = DummyMetric()
    circuit_breaker_state = DummyMetric()
