apiVersion: apps/v1
kind: Deployment
metadata:
  name: protonmail-bridge
  namespace: mail
  labels:
    app: protonmail-bridge
spec:
  replicas: 0
  selector:
    matchLabels:
      app: protonmail-bridge
  template:
    metadata:
      labels:
        app: protonmail-bridge
    spec:
      nodeSelector:
        kubernetes.io/hostname: racknerd-510bd9c
      tolerations:
        - key: pulse-only
          operator: Equal
          value: "true"
          effect: NoSchedule
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: bridge
          image: shenxn/protonmail-bridge:latest
          command:
            - sh
            - -c
            - |
              apk add --no-cache socat >/dev/null 2>&1
              if [ ! -f /root/.config/protonmail/bridge/prefs.json ]; then
                gpg --generate-key --batch /protonmail/gpgparams 2>/dev/null
                pass init pass-key 2>/dev/null
              fi
              socat TCP-LISTEN:25,fork TCP:127.0.0.1:1025 &
              socat TCP-LISTEN:143,fork TCP:127.0.0.1:1143 &
              rm -f /protonmail/faketty
              mkfifo /protonmail/faketty
              cat /protonmail/faketty | /usr/lib/protonmail/bridge/bridge --cli
          ports:
      volumes:
        - name: config
          hostPath:
            path: /mnt/mail/protonmail-bridge
            type: DirectoryOrCreate
