apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roundcube-data
  namespace: mail
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundcube
  namespace: mail
  labels:
    app: roundcube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roundcube
  template:
    metadata:
      labels:
        app: roundcube
    spec:
      nodeSelector:
        topology.researchstack.io/role: core
      containers:
        - name: roundcube
          image: roundcube/roundcubemail:latest
          ports:
            - containerPort: 80
          env:
            - name: ROUNDCUBEMAIL_DB_TYPE
              value: sqlite
            - name: ROUNDCUBEMAIL_DEFAULT_HOST
              value: "tls://mail.researchstack.info"
            - name: ROUNDCUBEMAIL_SMTP_SERVER
              value: "tls://mail.researchstack.info"
            - name: ROUNDCUBEMAIL_SKIN
              value: elastic
          volumeMounts:
            - name: data
              mountPath: /var/roundcube
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: roundcube-data
---
apiVersion: v1
kind: Service
metadata:
  name: roundcube
  namespace: mail
spec:
  type: NodePort
  selector:
    app: roundcube
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30808
