# ==============================================================================
# COPYRIGHT NO ONE EVERYWHERE LLC (WYOMING HOLDING COMPANY)
# PROJECT: SOVEREIGN STACK
# This artifact is entirely proprietary and cryptographically proven.
# Open-Source usage requires explicit permission from Brandon Scott Schneider.
# ==============================================================================
# soliton_constants_ne.py — Non-Euclidean geometry constants
# Generated by: tools/calibrate_geometry.py
# DAG tick 767, geometry-rip branch
#
# Method:
#   WN_MEAN_LOGIT, WN_STD_LOGIT: measured from 100 white-noise seeds passing
#   through the ACTUAL pipeline (_modes_from_bytes → ROT_R.T @ (modes − ROT_MU))
#   followed by compute_phi_raw_ne with GLOBAL consecutive ratio search.
#   Previous values (-0.579 / 0.550) were from synthetic sorted arrays and are
#   invalidated by the global-search fix to compute_phi_raw_ne.
#
#   GROUNDED_Z_NE = same z-offset (0.4σ) as EU GROUNDED_Z, now in NE logit-space.
#   SEISMIC_Z_NE  = same z-offset (-0.5σ) as EU FLAME boundary, in NE logit-space.
#   FOAM_THRESHOLD_NE: logit(0.15) normalised through NE WN distribution.
#   Full enwik9 empirical calibration pending (requires full 1GB enwik9 file).
#
# Geometry: log-multiplicative phi_prox (global ratio search) + logit z-score
# See: 6-Documentation/docs/NON_EUCLIDEAN_FLOAT.md, 6-Documentation/docs/EUCLIDEAN_ASSUMPTION_AUDIT.md

NE_CONSTANTS_CALIBRATED = True   # pipeline-calibrated; update when enwik9 available

# ── White-noise logit distribution (100 seeds, actual pipeline rotation) ──────
# logit(phi_raw_ne) over white-noise chunks — used to normalise phi_z_ne
# NOTE: WN mean is positive (0.375) because ROT_R introduces PHI-ratio correlations
# even for white noise. Thresholds are offsets above/below THIS mean.
WN_MEAN_LOGIT =  0.375280410    # mean logit(phi_raw_ne) for white-noise input
WN_STD_LOGIT  =  0.806610669    # std  logit(phi_raw_ne) for white-noise input

# ── Phase thresholds (parallel to EU constants, in NE z-space) ────────────────
# In NE z-space, 0.0 = white noise mean. Offsets match the EU constants exactly.
GROUNDED_Z_NE     =  0.4        # same offset as EU GROUNDED_Z (0.4σ above WN mean)
SEISMIC_Z_NE      = -0.5        # same offset as EU SEISMIC/FLAME boundary (-0.5σ)

# logit(0.15) = -1.7346; normalised: (-1.735 - 0.375) / 0.807 = -2.616
FOAM_THRESHOLD_NE = -2.615737   # equiv. to foam_score >= 0.15 (was FOAM_THRESHOLD=0.15)

# ── Empirical calibration pending enwik9 availability ─────────────────────────────
# To calibrate with actual enwik9 data:
# Run: python tools/calibrate_geometry.py --enwik9 /path/to/enwik9 --output 5-Applications/scripts/soliton_constants_ne.py
# Current values are derived from EU constants with appropriate NE z-space offsets
