#!/usr/bin/env python3
"""
Batch categorize Extracted models in MATH_MODEL_MAP.tsv
Updates Family and Bind_Class fields based on domain classification
"""

import re
from pathlib import Path

# Domain mappings: Family name -> (bind_class, domain_type)
DOMAIN_MAPPINGS = {
    # Genetics & Evolution (informational_bind)
    "Hardy-Weinberg": ("Population Genetics", "informational_bind", "LAYER_B_ROUTING"),
    "Arrhenius Eq": ("Thermodynamics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Central Dogma ODE": ("Genetics", "informational_bind", "LAYER_B_ROUTING"),
    "RNA Folding ΔG": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Replicator Eq": ("Evolutionary Dynamics", "informational_bind", "LAYER_J_DYNAMICS"),
    "Fisher's Theorem": ("Population Genetics", "informational_bind", "LAYER_B_ROUTING"),
    "Neutral Theory (Kimura)": ("Evolutionary Dynamics", "informational_bind", "LAYER_J_DYNAMICS"),
    "Price Equation": ("Evolutionary Dynamics", "informational_bind", "LAYER_J_DYNAMICS"),
    "Quasispecies Eq": ("Evolutionary Dynamics", "informational_bind", "LAYER_J_DYNAMICS"),
    "Wright-Fisher Drift": ("Population Genetics", "informational_bind", "LAYER_B_ROUTING"),
    "Genetic Toggle": ("Synthetic Biology", "control_bind", "LAYER_F_CONTROL"),
    "The Repressilator": ("Synthetic Biology", "control_bind", "LAYER_F_CONTROL"),
    "Feed-Forward Loop": ("Synthetic Biology", "control_bind", "LAYER_F_CONTROL"),
    "Competitive Exclusion": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Allee Effect": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Island Biogeography": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Hamilton's Rule": ("Evolutionary Dynamics", "informational_bind", "LAYER_B_ROUTING"),
    "Cope's Rule": ("Evolutionary Dynamics", "informational_bind", "LAYER_J_DYNAMICS"),
    "Clonal Selection": ("Immunology", "informational_bind", "LAYER_B_ROUTING"),
    "Viral Kinetics": ("Epidemiology", "informational_bind", "LAYER_J_DYNAMICS"),
    "Gompertz-Makeham": ("Demography", "informational_bind", "LAYER_B_ROUTING"),
    "Cancer Invasion": ("Oncology", "informational_bind", "LAYER_J_DYNAMICS"),
    "Mendelian Sum": ("Genetics", "informational_bind", "LAYER_B_ROUTING"),
    "Morgan Linkage": ("Genetics", "informational_bind", "LAYER_B_ROUTING"),
    "Polygenic CLT": ("Genetics", "informational_bind", "LAYER_B_ROUTING"),
    
    # Biophysics & Molecular (thermodynamic_bind)
    "Hill Equation": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Adair Equation": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "MWC Allostery": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "KNF Allostery": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Waddington Potential": ("Developmental Biology", "thermodynamic_bind", "LAYER_J_DYNAMICS"),
    "Gierer-Meinhardt": ("Developmental Biology", "thermodynamic_bind", "LAYER_J_DYNAMICS"),
    "Flux Balance (FBA)": ("Metabolism", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "MaxEnt Production": ("Thermodynamics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "MTE Master Eq": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Lifespan Scaling": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Reproductive Effort": ("Life History", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "ROS Damage": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Maturity Invariant": ("Life History", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Fecundity Ratio": ("Life History", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Energy Invariant": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Self-Assembly ΔG": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "CMC Threshold": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "DNA Tile Logic": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Anfinsen's Dogma": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Levinthal Space": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Folding Landscape": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Contact Order": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    
    # Neuroscience (control_bind)
    "Social Force Model": ("Behavioral Dynamics", "control_bind", "LAYER_F_CONTROL"),
    "Wolff's Law Equilibrium": ("Biomechanics", "physical_bind", "LAYER_L_APPLICATION"),
    "Izhikevich Neuron": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Kuramoto Synchrony": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Integrated Information": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Neuronal Workspace": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Objective Reduction": ("Quantum Biology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Behavioral Attractor": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Circadian Oscillator": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Weber-Fechner Law": ("Perception", "informational_bind", "LAYER_K_SIGNAL"),
    "Stevens' Power Law": ("Perception", "informational_bind", "LAYER_K_SIGNAL"),
    "Opponent Theory": ("Perception", "informational_bind", "LAYER_K_SIGNAL"),
    "Retinex Designator": ("Perception", "informational_bind", "LAYER_K_SIGNAL"),
    "Lateral Inhibition": ("Perception", "informational_bind", "LAYER_K_SIGNAL"),
    "CIELAB Mapping": ("Perception", "geometric_bind", "LAYER_K_SIGNAL"),
    "Brain Allometry": ("Neuroscience", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "EQ Index": ("Neuroscience", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Hick's Law": ("Cognitive Science", "informational_bind", "LAYER_B_ROUTING"),
    "Fitts's Law": ("Cognitive Science", "informational_bind", "LAYER_B_ROUTING"),
    "Zipf's Law": ("Information Theory", "informational_bind", "LAYER_A_COMPRESSION"),
    "Laughlin's Law": ("Neuroscience", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Hebb's Law": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Oja's Rule": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Hopfield Energy": ("Neuroscience", "thermodynamic_bind", "LAYER_G_ENERGY"),
    
    # Ecology & Population (informational_bind)
    "May's Stability": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Daisyworld Homeostasis": ("Ecology", "control_bind", "LAYER_F_CONTROL"),
    "Marginal Value Thm": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Pipe Model Theory": ("Botany", "geometric_bind", "LAYER_C_TOPOLOGY"),
    
    # Cardiovascular/Physiological (physical_bind) - LOW PRIORITY
    "Poiseuille's Law": ("Physiology", "physical_bind", "LAYER_L_APPLICATION"),
    "Starling's Law": ("Physiology", "physical_bind", "LAYER_L_APPLICATION"),
    "Fick Principle": ("Physiology", "physical_bind", "LAYER_L_APPLICATION"),
    "SA:V Scaling Law": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Membrane Tension": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "Osmotic Pressure": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "Muscle Force-Vel": ("Biomechanics", "physical_bind", "LAYER_L_APPLICATION"),
    "Nernst Potential": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "GHK Equation": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "Donnan Product": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "Gibbs-Duhem Eq": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Second Bio-Law": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    
    # Scaling Laws (geometric_bind) - LOW PRIORITY
    "WBE Branching": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Horton Number Law": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Horton Length Law": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "WBE Exponent": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Heart Rate Law": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Blood Volume Law": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    
    # Quantum/Biophysical (thermodynamic_bind) - LOW PRIORITY
    "Radical Pair Eq": ("Quantum Biology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Exciton Transfer": ("Quantum Biology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Proton Tunneling": ("Quantum Biology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    
    # Behavioral/Ecological (control_bind) - LOW PRIORITY
    "Sonar Ranging": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Auditory Filter": ("Perception", "informational_bind", "LAYER_K_SIGNAL"),
    "Kinematic Replication": ("Developmental Biology", "control_bind", "LAYER_F_CONTROL"),
    "Vicsek Swarming": ("Behavioral Dynamics", "control_bind", "LAYER_F_CONTROL"),
    "Lévy Flight": ("Behavioral Dynamics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Cable Equation": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    
    # Other models - assign based on context
    "Morpho-Transform": ("Developmental Biology", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Murray's Law": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    
    # Ecology & Population (informational_bind/control_bind)
    "Growth Dilution": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Redfield Ratio": ("Biogeochemistry", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Holling Response": ("Ecology", "control_bind", "LAYER_F_CONTROL"),
    "Eco-Connectance": ("Ecology", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Taylor's Law": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Logistic Map": ("Ecology", "control_bind", "LAYER_F_CONTROL"),
    "Lotka's Invariant": ("Demography", "informational_bind", "LAYER_B_ROUTING"),
    "Tetz's Law": ("Evolutionary Biology", "informational_bind", "LAYER_J_DYNAMICS"),
    "Survival Limit": ("Demography", "informational_bind", "LAYER_B_ROUTING"),
    "Genomic Entropy": ("Genetics", "informational_bind", "LAYER_A_COMPRESSION"),
    "Codon Hamming": ("Genetics", "informational_bind", "LAYER_B_ROUTING"),
    "Bio-Capacity": ("Genetics", "informational_bind", "LAYER_B_ROUTING"),
    "Error Catastrophe": ("Evolutionary Biology", "informational_bind", "LAYER_J_DYNAMICS"),
    "Bio-Hamiltonian": ("Evolutionary Biology", "control_bind", "LAYER_F_CONTROL"),
    "Requisite Variety": ("Control Theory", "control_bind", "LAYER_F_CONTROL"),
    "Bio-Reinforcement": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Pareto Robustness": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Limit Cycle Thm": ("Dynamical Systems", "control_bind", "LAYER_F_CONTROL"),
    "Phase Singularity": ("Dynamical Systems", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Hawk-Dove ESS": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Van Valen's Law": ("Evolutionary Biology", "informational_bind", "LAYER_J_DYNAMICS"),
    "Scale-Free Dist": ("Network Theory", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Preferential Att": ("Network Theory", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Neutrality Rule": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Adami Complexity": ("Evolutionary Biology", "informational_bind", "LAYER_A_COMPRESSION"),
    "Regulatory Law": ("Genetics", "informational_bind", "LAYER_B_ROUTING"),
    "Revelle Factor": ("Biogeochemistry", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Remineral Ratio": ("Biogeochemistry", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Small-World Law": ("Network Theory", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Modularity Q": ("Network Theory", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "HOT Principle": ("Complexity Theory", "control_bind", "LAYER_F_CONTROL"),
    "Complexity Law": ("Complexity Theory", "informational_bind", "LAYER_A_COMPRESSION"),
    "GK-Switch": ("Biophysics", "control_bind", "LAYER_F_CONTROL"),
    "Mitotic Oscillator": ("Cell Biology", "control_bind", "LAYER_F_CONTROL"),
    "PER-CRY Feedback": ("Circadian Biology", "control_bind", "LAYER_F_CONTROL"),
    "Keller-Segel": ("Developmental Biology", "control_bind", "LAYER_F_CONTROL"),
    "Epigenetic Clock": ("Epigenetics", "informational_bind", "LAYER_B_ROUTING"),
    "Kinetic Proofread": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Biodiversity Num": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Critical Power Law": ("Complexity Theory", "informational_bind", "LAYER_A_COMPRESSION"),
    "Broken Stick": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Niche Breadth": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Niche Overlap": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Motor Efficiency": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Parrondo Paradox": ("Game Theory", "control_bind", "LAYER_F_CONTROL"),
    "Somite Size Law": ("Developmental Biology", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Morphogen Scaling": ("Developmental Biology", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "MDDR Growth Law": ("Developmental Biology", "control_bind", "LAYER_F_CONTROL"),
    "Fermat's Path Law": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Max Flux Principle": ("Metabolism", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Max Power Law": ("Thermodynamics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Least Action Law": ("Physics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Action Functional": ("Physics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "CSD Autocorr": ("Complexity Theory", "informational_bind", "LAYER_A_COMPRESSION"),
    "CSD Variance": ("Complexity Theory", "informational_bind", "LAYER_A_COMPRESSION"),
    "Recovery Rate": ("Ecology", "control_bind", "LAYER_F_CONTROL"),
    "Resilience Basin": ("Ecology", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Sensing Limit": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "Signaling SNR": ("Biophysics", "informational_bind", "LAYER_K_SIGNAL"),
    "Positional Noise": ("Biophysics", "informational_bind", "LAYER_K_SIGNAL"),
    "Oregonator BZ": ("Chemical Physics", "control_bind", "LAYER_F_CONTROL"),
    "Firefly Synchrony": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Bio-Continuity": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "Strouhal Number": ("Biomechanics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Froude Number": ("Biomechanics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Huxley Muscle Law": ("Biomechanics", "physical_bind", "LAYER_L_APPLICATION"),
    "Monod Equation": ("Microbiology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Pirt's Law": ("Microbiology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Verhulst Logistic": ("Ecology", "control_bind", "LAYER_F_CONTROL"),
    "Gompertz Growth": ("Ecology", "control_bind", "LAYER_F_CONTROL"),
    "MCA Control Coeff": ("Metabolism", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "MCA Summation": ("Metabolism", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Perfect Adapt": ("Control Theory", "control_bind", "LAYER_F_CONTROL"),
    "Demand Rule": ("Genetics", "control_bind", "LAYER_F_CONTROL"),
    "Place Theory": ("Perception", "informational_bind", "LAYER_K_SIGNAL"),
    "Traveling Wave": ("Perception", "geometric_bind", "LAYER_K_SIGNAL"),
    "Tonotopic Map": ("Perception", "geometric_bind", "LAYER_K_SIGNAL"),
    "Cochlear Amp": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "R* Theory": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "SM Correlation": ("Demography", "informational_bind", "LAYER_B_ROUTING"),
    "Vitality Decay": ("Demography", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Mortality Plateau": ("Demography", "informational_bind", "LAYER_B_ROUTING"),
    "Bark Scale": ("Perception", "informational_bind", "LAYER_K_SIGNAL"),
    "Crit Bandwidth": ("Perception", "informational_bind", "LAYER_K_SIGNAL"),
    "Equal Loudness": ("Perception", "informational_bind", "LAYER_K_SIGNAL"),
    "Niche Hypervolume": ("Ecology", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Nernst-Planck": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "Richness Scaling": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "FHN Excitability": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Swift-Hohenberg": ("Pattern Formation", "control_bind", "LAYER_F_CONTROL"),
    "Tissue Stiffness": ("Biomechanics", "physical_bind", "LAYER_L_APPLICATION"),
    "Cytoskeletal F": ("Biomechanics", "physical_bind", "LAYER_L_APPLICATION"),
    "Spiral Vogel": ("Botany", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Golden Angle": ("Botany", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Hofmeister Rule": ("Botany", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Muller's Ratchet": ("Evolutionary Biology", "informational_bind", "LAYER_J_DYNAMICS"),
    "Neutral Diversity": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Reynolds Number": ("Fluid Dynamics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Peclet Number": ("Fluid Dynamics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Darcy's Law": ("Fluid Dynamics", "physical_bind", "LAYER_L_APPLICATION"),
    "Starling Eq": ("Physiology", "physical_bind", "LAYER_L_APPLICATION"),
    "Handicap Principle": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Honesty Condition": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Honest Equilibrium": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Schwan Equation": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "Cole-Cole Eq": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "Dispersion Law": ("Physics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "RNA Combinators": ("Synthetic Biology", "control_bind", "LAYER_F_CONTROL"),
    "BioBrick Logic": ("Synthetic Biology", "control_bind", "LAYER_F_CONTROL"),
    "Genetic Load": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Critical Depth": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Particle Sinking": ("Oceanography", "physical_bind", "LAYER_L_APPLICATION"),
    "Q10 Rule": ("Biophysics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Base Saturation": ("Biogeochemistry", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Hyphal Flow": ("Mycology", "physical_bind", "LAYER_L_APPLICATION"),
    "Terraced Barrel": ("Botany", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Reliability Law": ("Engineering", "informational_bind", "LAYER_B_ROUTING"),
    "Reaction Prop": ("Chemistry", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Gillespie Step": ("Stochastic Processes", "control_bind", "LAYER_F_CONTROL"),
    "Master Equation": ("Statistical Mechanics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Masking Slope": ("Perception", "informational_bind", "LAYER_K_SIGNAL"),
    "SMR Priority": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Specific Loudness": ("Perception", "informational_bind", "LAYER_K_SIGNAL"),
    "STDP Law": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Trophic 10% Rule": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Slender-Body F": ("Fluid Dynamics", "physical_bind", "LAYER_L_APPLICATION"),
    "DVM Fitness": ("Marine Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Swim Response": ("Marine Biology", "control_bind", "LAYER_F_CONTROL"),
    "Turbulent Encounter": ("Fluid Dynamics", "physical_bind", "LAYER_L_APPLICATION"),
    "Patch Residence": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Input Matching": ("Foraging Theory", "informational_bind", "LAYER_B_ROUTING"),
    "Fitness Equi": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "V-Formation Upwash": ("Aerodynamics", "physical_bind", "LAYER_L_APPLICATION"),
    "Induced Drag Law": ("Aerodynamics", "physical_bind", "LAYER_L_APPLICATION"),
    "Flight Efficiency": ("Aerodynamics", "physical_bind", "LAYER_L_APPLICATION"),
    "Reproduction Num": ("Demography", "informational_bind", "LAYER_B_ROUTING"),
    "Herd Immunity": ("Epidemiology", "informational_bind", "LAYER_B_ROUTING"),
    "SIR Dynamics": ("Epidemiology", "control_bind", "LAYER_F_CONTROL"),
    "NDZ Model": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Root Uptake": ("Plant Physiology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Root Fractal": ("Plant Physiology", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Constructal Law": ("Physics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Muscle Mechanics": ("Biomechanics", "physical_bind", "LAYER_L_APPLICATION"),
    "Square-Cube Law": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Fung's Law": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Alveolar Laplace": ("Physiology", "physical_bind", "LAYER_L_APPLICATION"),
    "Ventricular Wall": ("Physiology", "physical_bind", "LAYER_L_APPLICATION"),
    "Process S": ("Metabolism", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Process C": ("Metabolism", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Aschoff's Rule": ("Chronobiology", "control_bind", "LAYER_F_CONTROL"),
    "Lack's Principle": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Smith-Fretwell": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Repro Scaling": ("Evolutionary Biology", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Dunbar's Law": ("Social Neuroscience", "informational_bind", "LAYER_B_ROUTING"),
    "Relationship Law": ("Social Science", "informational_bind", "LAYER_B_ROUTING"),
    "Brain Curvature": ("Neuroscience", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Glottal Bernoulli": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "Source-Filter": ("Speech Science", "informational_bind", "LAYER_K_SIGNAL"),
    "Pitch Scaling": ("Speech Science", "informational_bind", "LAYER_K_SIGNAL"),
    "VTL Scaling": ("Speech Science", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Tissue Fluence": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "Luciferase Law": ("Molecular Biology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Beer-Lambert": ("Chemistry", "physical_bind", "LAYER_L_APPLICATION"),
    "Cole's Paradox": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Maturity Ratio": ("Life History", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Allocation Law": ("Life History", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Euler-Lotka Eq": ("Demography", "informational_bind", "LAYER_B_ROUTING"),
    "Rescorla-Wagner": ("Psychology", "control_bind", "LAYER_F_CONTROL"),
    "Cognitive Lévy": ("Cognitive Science", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Cognitive MVT": ("Foraging Theory", "informational_bind", "LAYER_B_ROUTING"),
    "SAM Probability": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Gouy-Stodola": ("Thermodynamics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "MinEnt Prod": ("Thermodynamics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "MaxEnt Prod": ("Thermodynamics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Useful Work": ("Thermodynamics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Corner's Law": ("Ecology", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Pipe Model": ("Botany", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Cavitation Law": ("Fluid Dynamics", "physical_bind", "LAYER_L_APPLICATION"),
    "Species-Area Law": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Cell Prestress": ("Biomechanics", "physical_bind", "LAYER_L_APPLICATION"),
    "Reciprocal Yield": ("Agriculture", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Noble Model": ("Cardiac Physiology", "control_bind", "LAYER_F_CONTROL"),
    "Gating Dynamics": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Inward Rectifier": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "Stevens' 3/2 Law": ("Perception", "informational_bind", "LAYER_K_SIGNAL"),
    "White Matter Law": ("Neuroscience", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Rall's 3/2 Law": ("Neuroscience", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Synaptic Invariant": ("Neuroscience", "informational_bind", "LAYER_B_ROUTING"),
    "Multi-Hit Law": ("Radiation Biology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "MCA Elasticity": ("Metabolism", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Connectivity Thm": ("Network Theory", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Price Selection": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Reichardt Detect": ("Vision Science", "informational_bind", "LAYER_K_SIGNAL"),
    "ACO Transition": ("Chemistry", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Pheromone Law": ("Chemical Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Donachie Rule": ("Cell Biology", "control_bind", "LAYER_F_CONTROL"),
    "Cell Size Law": ("Cell Biology", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Adder Principle": ("Cell Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Wright's Gradient": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Mean Fitness": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "SBT Drift": ("Evolutionary Biology", "informational_bind", "LAYER_J_DYNAMICS"),
    "Amari Neural Field": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Mexican Hat Kernel": ("Neuroscience", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Sigmoid Activity": ("Neuroscience", "control_bind", "LAYER_F_CONTROL"),
    "Shell Spiral Law": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Mass Action Law": ("Chemistry", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Equilibrium Invariant": ("Thermodynamics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Malthusian Law": ("Demography", "control_bind", "LAYER_F_CONTROL"),
    "Hayflick Limit": ("Cell Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Senescence Rule": ("Gerontology", "informational_bind", "LAYER_B_ROUTING"),
    "Sheldon Spectrum": ("Oceanography", "informational_bind", "LAYER_B_ROUTING"),
    "Inverse Mass N": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Productivity Law": ("Ecology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Fisher FGM Potential": ("Evolutionary Biology", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Beneficial Prob": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Small Mutation Law": ("Evolutionary Biology", "informational_bind", "LAYER_J_DYNAMICS"),
    "Complexity Cost": ("Evolutionary Biology", "informational_bind", "LAYER_A_COMPRESSION"),
    "Gene Family Law": ("Genetics", "informational_bind", "LAYER_B_ROUTING"),
    "Functional Scale": ("Evolutionary Biology", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "BDIM Dynamics": ("Evolutionary Biology", "control_bind", "LAYER_F_CONTROL"),
    "Margalef Index": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Shannon Index": ("Ecology", "informational_bind", "LAYER_A_COMPRESSION"),
    "Info-Stability": ("Information Theory", "informational_bind", "LAYER_A_COMPRESSION"),
    "Info-Shedding": ("Information Theory", "informational_bind", "LAYER_A_COMPRESSION"),
    "Drake's Rule": ("Evolutionary Biology", "informational_bind", "LAYER_B_ROUTING"),
    "Minimal Genome": ("Genetics", "informational_bind", "LAYER_B_ROUTING"),
    "Effective Info": ("Information Theory", "informational_bind", "LAYER_A_COMPRESSION"),
    "Constrained TEE": ("Thermodynamics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Metabolic Ceiling": ("Metabolism", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Metabolic Scope": ("Metabolism", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Droop Equation": ("Microbiology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Herbert's Law": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Quota Dynamics": ("Ecology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Homeostatic Eq": ("Physiology", "control_bind", "LAYER_F_CONTROL"),
    "Damuth's Law": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Unified Metab": ("Metabolism", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Minimum Volume": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Locomotion Speed": ("Biomechanics", "physical_bind", "LAYER_L_APPLICATION"),
    "Movement Freq": ("Biomechanics", "physical_bind", "LAYER_L_APPLICATION"),
    "Diffusion Speed": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "Rubisco Limit": ("Plant Physiology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "RuBP Regen": ("Plant Physiology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Ball-Berry Law": ("Plant Physiology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Intrinsic WUE": ("Plant Physiology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Light Response": ("Plant Physiology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Reed-Frost Law": ("Epidemiology", "control_bind", "LAYER_F_CONTROL"),
    "Trophic Wave": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Trophic Kinetic": ("Ecology", "control_bind", "LAYER_F_CONTROL"),
    "Movement Freq": ("Biomechanics", "physical_bind", "LAYER_L_APPLICATION"),
    "Diffusion Speed": ("Biophysics", "physical_bind", "LAYER_L_APPLICATION"),
    "Rubisco Limit": ("Plant Physiology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "RuBP Regen": ("Plant Physiology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Ball-Berry Law": ("Plant Physiology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Intrinsic WUE": ("Plant Physiology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Light Response": ("Plant Physiology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Boltzmann State Weighting": ("Statistical Mechanics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Rubric-as-Reward (RaR)": ("Machine Learning", "agent_bind", "LAYER_M_LEAN_SEMANTICS"),
    "Global Metric Learning (GML)": ("Machine Learning", "metric_bind", "LAYER_M_LEAN_SEMANTICS"),
    "Equation Chain (YEC)": ("Logic", "logic_bind", "LAYER_M_LEAN_SEMANTICS"),
    "Differential Spectral Correction (DSC)": ("Signal Processing", "signal_bind", "LAYER_K_SIGNAL"),
    "Autogenetic Update Rule": ("Agent Logic", "agent_bind", "LAYER_M_LEAN_SEMANTICS"),
    "Autogenetic_Update_Rule": ("Agent Logic", "agent_bind", "LAYER_M_LEAN_SEMANTICS"),
    "Liebig's Law": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "Shelford Tolerance": ("Ecology", "informational_bind", "LAYER_B_ROUTING"),
    "French Flag Model": ("Developmental Biology", "control_bind", "LAYER_F_CONTROL"),
    "SDD Gradient": ("Developmental Biology", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Lewis's Law": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Aboav-Weaire Law": ("Biophysics", "geometric_bind", "LAYER_C_TOPOLOGY"),
    "Drift-Barrier": ("Evolutionary Biology", "informational_bind", "LAYER_J_DYNAMICS"),
    "Drift_Barrier": ("Evolutionary Biology", "informational_bind", "LAYER_J_DYNAMICS"),
    "Fick's Law": ("Thermodynamics", "thermodynamic_bind", "LAYER_G_ENERGY"),
    "Jarzynski Equality": ("Thermodynamics", "thermodynamic_bind", "LAYER_G_ENERGY"),
}

def main():
    tsv_path = Path(__file__).resolve().parent.parent.parent / "3-Mathematical-Models" / "MATH_MODEL_MAP.tsv"
    
    with open(tsv_path, 'r') as f:
        lines = f.readlines()
    
    updated_count = 0
    still_extracted = 0
    
    for i, line in enumerate(lines):
        if i == 0:  # Skip header
            continue
        
        # Split by tab, handling potential edge cases
        parts = line.rstrip('\n').split('\t')
        if len(parts) < 11:
            continue
        
        # Column indices (0-based):
        # 0: ID, 1: Model_Name, 2: Family, 3: Equation, 4: Variables
        # 5: Purpose, 6: Location, 7: Implemented, 8: Status
        # 9: Cross_Refs, 10: Domain_Type, 11: Bind_Class
        model_name = parts[1]
        family = parts[2]
        bind_class = parts[11] if len(parts) > 11 else ""
        domain_type = parts[10] if len(parts) > 10 else ""
        
        # Debug: print first few lines
        if i < 5:
            print(f"Line {i}: model={model_name}, family={family}, bind={bind_class}")
        
        # Only process "Extracted" models
        if family == "Extracted":
            if model_name in DOMAIN_MAPPINGS:
                new_family, new_bind, new_domain = DOMAIN_MAPPINGS[model_name]
                parts[2] = new_family
                parts[11] = new_bind
                # Also update Domain_Type if it's missing or generic
                if domain_type == "" or domain_type == "unknown":
                    parts[10] = new_domain
                
                lines[i] = '\t'.join(parts) + '\n'
                updated_count += 1
                print(f"Updated: {model_name} -> {new_family} ({new_bind})")
            else:
                still_extracted += 1
    
    with open(tsv_path, 'w') as f:
        f.writelines(lines)
    
    print(f"\nSummary:")
    print(f"  Updated: {updated_count} models")
    print(f"  Still unmapped: {still_extracted} models")

if __name__ == "__main__":
    main()
