apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual-budget
  namespace: services
  labels:
    app: actual-budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actual-budget
  template:
    metadata:
      labels:
        app: actual-budget
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: actual-budget
        image: ghcr.io/actualbudget/actual-server:26.5.2
        ports:
        - containerPort: 5006
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: actual-budget-data
