apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - registry-api/deployment.yaml
  - registry-api/service.yaml
  - jobs-api/deployment.yaml
  - jobs-api/service.yaml
  - blobs-api/deployment.yaml
  - blobs-api/service.yaml
