PACKAGE_NAME="qfox-topology-manager"
PACKAGE_VERSION="0.1.0"

BUILT_MODULE_NAME[0]="qfox_topology_manager"
DEST_MODULE_LOCATION[0]="/kernel/extra"
AUTOINSTALL="yes"

MAKE[0]="make KVER=${kernelver}"
CLEAN="make clean KVER=${kernelver}"
